AudiovisualMetadataPlatform/amppd-ui

- .env
- .eslintrc.js
- src/components/WorkflowSelection.vue
- src/main.js
- src/store/workflow-submission-store.js
Added support for environment variables in vue.js.  
Documentation can be found [here](https://cli.vuejs.org/guide/mode-and-env.html)
At the root of the ammpd-ui project, create a file similar to attached named .env.local, which can point to a specific URL for the amp api.  This file is ignored by git.
[.env.local](https://github.com/AudiovisualMetadataPlatform/amppd-ui/files/3799457/env.local.txt)
> Adding environment variables

- package.json
- src/components/Login.vue
- src/components/Register.vue
- src/main.js
Adds client side validation of credentials. Changes register and auth requests to posts
> Amp 498 credential validation

- package.json
- src/components/Workflow.vue
- src/store/workflow-submission-store.js
> AMP-486: add more info (step ID, readable toolId, step annotation) to

- src/components/ForgotPassword.vue
- src/components/ResetPassword.vue
Added a function to fetch email id and prepopulate it on the reset password page. Also added logging to some files
> Amp 585 prepopulate email

- src/components/batch/BatchIngest.vue
This is a small change to list all processing errors on front end
> Amp 587 batch ingest fixes

- package.json
> Amp 655 package dependencies

- src/components/account/Login.vue
> Minor link change

- src/components/account/Register.vue
- src/service/account-service.js
Refactoring front end logic to use username, email, and first/last name
> Amp 722 refactoring login

- src/components/dashboard/Dashboard.vue
- src/components/dashboard/DashboardFilters/SearchFilter.vue
- src/components/dashboard/DashboardTable.vue
- src/components/navigation/Sidebar.vue
- src/components/shared/TypeAhead.vue
- src/router.js
- src/service/dashboard-service.js
Adds parameter to typeahead to allow for different types of search.  Adds clear all button to filters. Fixes sidebar navigation link.
> Search filter updates

- src/components/dashboard/DashboardFilters/SearchFilter.vue
- src/components/shared/TypeAhead.vue
> Fixing type ahead bug

- src/components/dashboard/DashboardFilters/SubmitterFilter.vue
- src/components/shared/TypeAhead.vue
Includes the additional UI to typeahead and submitter filter
> Amp 758 part2

- package-lock.json
- src/components/workflow/SelectFiles.vue
- src/components/workflow/SelectWorkflow.vue
- src/components/workflow/Workflow.vue
- src/service/workflow-service.js
- src/store/amp-store.js
Removing no longer used code, references.  Fixes visual bug to file selection filters.  Fixes bug to file searching.  Renamed SelectFilesLeft and SelectWorkflowsRight to SelectFiles and SelectWorkflow.
> Amp 837 workflow refactor

- src/components/workflow/SelectBundle.vue
- src/components/workflow/SelectFiles.vue
- src/components/workflow/SelectWorkflow.vue
- src/store/amp-store.js
> AMP-844: update logic to allow bundle list refresh upon showing select

- public/css/style.css
- src/components/workflow/SelectBundle.vue
- src/components/workflow/SelectFiles.vue
- src/components/workflow/SelectWorkflow.vue
Modifies the file names to show an ellipsis when the file name becomes too long.  Also adds a tooltip when file names are hovered on.
> Amp 853 long file names

- src/components/hmgm/NerEditor.vue
- src/components/hmgm/TokenValidator.vue
- src/components/hmgm/TranscriptEditor.vue
- src/helpers/request-options.js
- src/service/base-service.js
- src/service/hmgm-service.js
Adds front end support for token validation to the NER and Transcript editors.  Users are required to supply a validation token before viewing the editor.  Once a token has been validated it is stored in local storage. Subsequent requests to that page will validate the token without requiring user input.
> Amp 710 editor auth

- package-lock.json
- src/components/hmgm/NerEditor.vue
Requiring iframe url before displaying iframe
> NER Editor changes

- src/components/dashboard/DashboardTable.vue
- src/components/deliverables/Deliverables.vue
- src/service/workflow-result-service.js
Renaming dashboard to WorkflowResult.
> AMP-870: Renaming Dashboard to WorkflowResult

- src/service/workflow-service.js
Calls encodeURIComponent on searchWord before making api call to search primary files.
> AMP-894 Search fails with # character

- public/css/style.css
- src/components/dashboard/DashboardTable.vue
Adds "Deleted" status in dashboard.
> AMP-927 Job Status in Dashboard

- src/components/dashboard/DashboardFilters/FileFilter.vue
- src/components/dashboard/DashboardFilters/ItemFilter.vue
- src/components/dashboard/DashboardFilters/SearchFilter.vue
- src/components/dashboard/DashboardFilters/StatusFilter.vue
- src/components/dashboard/DashboardFilters/StepFilter.vue
- src/components/dashboard/DashboardFilters/SubmitterFilter.vue
- src/components/dashboard/DashboardFilters/WorkflowFilter.vue
- src/components/dashboard/DashboardTable.vue
- src/components/deliverables/Deliverables.vue
- src/service/workflow-result-service.js
Fixes the clear all fix by removing local references to selected properties from each filter.  Consolidates the functions to generate media/output links into service class.
> Amp 915 filter clear fix

- src/components/workflow/SelectWorkflow.vue
Adds error messaging to workflow submission modal when errors occur.
> Adding error messaging to workflow submission modal

- .env.staging
- .env.test
API endpoints to start with /rest
> Amp 954 rest endpoint change

- src/components/dashboard/DashboardFilters/DateFilter.vue
- src/components/workflow/Workflow.vue
- src/store/amp-store.js
On page load, clear the list of files to be submitted.
> Clearing submitted files on page load

- src/components/collections/CollectionDetails.vue
- src/components/collections/CollectionDetailsItemCard.vue
- src/components/collections/Collections.vue
- src/router.js
- src/service/collection-detail-service.js
- src/store/amp-store.js
Implemented collection details page.
> AMP 1361 Collection detail page implementation

- src/components/shared/Search.vue
- Search not working in
1. Search Collections in the Unit page
2. Search Items in the Collections page.
> AMP-1855: Search not working

- src/components/dashboard/Dashboard.vue
- src/components/dashboard/DashboardTable.vue
- src/components/evaluation/GroundTruthModal.vue
- src/components/evaluation/MGMevaluation.vue
- src/components/evaluation/NewTest.vue
- src/components/navigation/Sidebar.vue
- src/components/shared/Search.vue
- src/components/workflow/SelectFiles.vue
- src/service/evaluation-service.js
- src/store/state.js
> Implement MGM Evaluation New Test page & Bug fixing

- .env
- src/components/dashboard/Dashboard.vue
- src/components/dashboard/DashboardTable.vue
- src/components/entity/EntityList.vue
- src/components/entity/ItemFiles.vue
- src/components/navigation/Sidebar.vue
- src/router.js
- src/service/entity-service.js
- src/store/state.js
> Implementation: AMP-2075/AMP-2219/AMP-2252/AMP-2217/AMP-2127

- src/components/entity/EntityList.vue
- src/components/unused/WorkflowSelection.vue
- src/components/workflow/SelectWorkflow.vue
- src/components/workflow/WorkflowList.vue
> AMP-1987/2263: Add label to toggle & Frontend work for "creator" field

- package-lock.json
- package.json
- src/components/evaluation/BarChart.vue
- src/components/evaluation/NewTest.vue
- src/components/evaluation/TestResults.vue
- src/components/evaluation/TestResultsVisualiz.vue
- src/router.js
- src/service/evaluation-service.js
- src/service/shared-service.js
> AMP-2384/2387: Implement visualization page -- review scores & Implement Review Outputs view

- src/components/deliverables/Deliverables.vue
- src/components/entity/ItemFiles.vue
- src/components/shared/Search.vue
- src/components/workflow/WorkflowList.vue
- src/service/workflow-service.js
> [AMP-1857+AMP-2525]: Search workflows - frontend  &&  Add Alias to Deliverables page

- package-lock.json
- package.json
- src/assets/constants/common-contant.js
- src/components/navigation/Sidebar.vue
- src/components/shared/Header.vue
- src/components/shared/Logout.vue
- src/service/account-service.js
- src/service/shared-service.js
When user is logged in and has a `firstName` and a `lastName` to derive user initials:
When user is logged in and doesn't have a `firstName` and a `lastName` to derive user initial:
When logged out:
> AMP-2558: Offer explicit sign out option to users

- src/components/entity/ItemSearch.vue
- src/service/access-control-service.js
- src/service/item-service.js
- update API URL
- update handling of item/unit response
> AMP-2539/2642

- public/css/style.css
- src/assets/constants/common-contant.js
- src/components/navigation/Sidebar.vue
- src/components/shared/Logout.vue
Add `Configuration` to nav:
Move `Batch Ingest` to `Content` menu:
> Add Configuration and move Batch Ingest to Content in nav

- src/components/entity/EntityList.vue
- src/components/shared/Search.vue
> AMP-2824: fix bugs due to missing sync on AC data in entitylist and

- src/components/account/Login.vue
- src/components/dashboard/Dashboard.vue
- src/components/entity/EntityList.vue
- fix content page width issue
- improve activtation response
- remove commented code
> AMP-3079/3267

- components.d.ts
- src/components/shared/BreadCrumbs.vue
- src/helpers/env.js
- src/router.js
Changes made in the PR:
- added Bootstrap 5 class 1float-end1 to 1b-breadcrumbs1 component to right align
- changed the router to fix the link paths in the breadcrumbs to fix navigation
- change `b-breadcrumb` implementation by using `b-breadcrumb-item` and `b-link` with `replace` prop to build the breadcrumbs to fix routing
- fix `config is undefined` error when some pages are refreshed
> Fix breadcrumbs

- components.d.ts
- src/components/evaluation/MGMevaluation.vue
- src/components/evaluation/NewTest.vue
- src/components/evaluation/TestResultsVisualiz.vue
- src/components/workflow/WorkflowList.vue
- src/styles/style.css
Need to test, evaluation test result page before merging. Right now, there are no test results in `amp-devel` to test this. This is waiting on https://iu-uits.atlassian.net/browse/AMP-3591 is fixed.
> Fix classes for tab views and cleanup CSS

- components.d.ts
- src/components/evaluation/MGMevaluation.vue
- src/components/evaluation/NewTest.vue
- src/components/evaluation/TestResultsVisualiz.vue
- src/components/workflow/WorkflowList.vue
- src/styles/style.css
Reverts AudiovisualMetadataPlatform/amppd-ui#575
> Revert "Fix classes for tab views and cleanup CSS"

- src/components/account/ApproveUser.vue
- src/components/account/ForgotPassword.vue
- src/components/account/Login.vue
- src/components/account/Register.vue
- src/components/account/ResetPassword.vue
- src/components/evaluation/NewTest.vue
- src/components/shared/Search.vue
- src/components/workflow/SaveBundle.vue
- src/components/workflow/SelectFiles.vue
- src/service/account-service.js
- src/styles/style.css
Related issue: https://iu-uits.atlassian.net/browse/AMP-3593
This PR needs to be reviewed together with @yingfeng-iu
> Use Bootstrap form validation and cleanup link and form CSS

- src/router.js
- src/service/base-service.js
- add logic to clearout login info if user timeout and tries to access home
- replace router.push with next in router.beforeEach
> AMP-3531/AMP-3082:

- src/components/entity/EntityList.vue
- src/components/hmgm/NerEditor.vue
- src/components/hmgm/TokenValidator.vue
- src/components/hmgm/TranscriptEditor.vue
- src/helpers/request-options.js
- src/service/hmgm-service.js
- changes related to HMGM auth token
- rename params and change params order
> AMP-3266/3681

- components.d.ts
- package.json
- src/components/hmgm/BBCTranscriptEditorWrapper.vue
- src/components/hmgm/TranscriptEditor.vue
Reverts AudiovisualMetadataPlatform/amppd-ui#607
> AMP-3256 2nd attempt on "Import BBC transcript editor back into the UI after resolving build i…""

- src/components/hmgm/BBCTranscriptEditorWrapper.vue
- src/components/hmgm/TranscriptEditor.vue
Reverts AudiovisualMetadataPlatform/amppd-ui#610
> Revert "Use react-dom 17.x code to render react-transcript-edior"

- src/components/entity/EntityList.vue
- src/components/entity/ItemFiles.vue
- src/components/shared/Logout.vue
- src/service/access-control-service.js
- src/service/account-service.js
- src/service/collection-service.js
- src/service/entity-service.js
- src/service/item-service.js
- src/service/primary-file-service.js
- src/service/unit-service.js
- src/store/state.js
- add delete button and confirmation modal to EntityList
- handle delete button and confirmation modal
- add shared API call and util methods to entity-service
> AMP-3513/AMP-3512/AMP-3564/AMP-3563

- src/components/entity/EntityList.vue
- src/components/workflow/WorkflowList.vue
- add mt to Active checkbox (not effective)
- dont display delete if no unit selected or new unit unsaved
> AMP-3627/AMP-3728
